name: notary_admin
description: AMS project
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  lazy_paginated_data_table: ^0.0.7
  file_picker: ^5.2.9
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.2.1
  path_provider: ^2.0.14
  omni_datetime_picker: ^0.1.4
  device_preview: ^1.1.0
  month_year_picker: ^0.2.0+3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0
  html_editor_enhanced: ^2.5.1
  flutter_downloader: ^1.10.2
  
  notary_model:
    path: ../notary_model
  http_error_handler: ^0.0.1
  rapidoc_maps_plugin:
    path: ../rapidoc_maps_plugin
  rapidoc_utils:
    path: ../rapidoc_utils
  devicelocale: ^0.6.0
 # quill_html_editor: ^2.1.8
  webviewx: ^0.2.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.11.0
  build_runner: any
  retrofit: ^3.0.1
  retrofit_generator: ^4.0.1
  byte_util: ^0.3.0

  #flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true



  assets:
    # Add assets from the images directory to the application.
    - assets/images/profile.png
    - assets/images/store.png
    - assets/images/store_marker.png
    - assets/images/no-image.png
    - assets/images/promotion.jpg
    - assets/images/logo.png
    - assets/images/logo-no-bg.png
    - assets/images/pin.png
    - assets/countries.json
