name: notary_admin
description: AMS project
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: 10.1.0
  get_it: ^7.2.0
  rxdart: ^0.27.3
  dio: ^4.0.0
  path_provider: ^2.0.2
  dio_cookie_manager: ^2.0.0
  web_socket_channel: ^2.1.0
  url_launcher: ^6.0.2
  share: ^2.0.4
  expandable: ^5.0.1
  maps_launcher: ^2.0.0
  extended_image_library: ^3.1.0
  fluro: ^2.0.3
  universal_html: ^2.0.8
  shared_preferences: ^2.0.6
  flutter_responsive_tools: ^0.0.1
  infinite_scroll_list_view: ^1.0.0
  badges: ^2.0.3
  time_planner: ^0.1.1
  time_picker_sheet: ^0.0.2+1
  device_preview: ^1.1.0
  month_year_picker: ^0.2.0+3
  horizontal_data_table: ^4.1.4
  # firebase
  firebase_messaging: ^14.2.0
  lazy_paginated_data_table: ^0.0.7

  notary_model:
    path: ../notary_model
  http_error_handler: ^0.0.1
  rapidoc_maps_plugin:
    path: ../rapidoc_maps_plugin
  rapidoc_utils:
    path: ../rapidoc_utils
  devicelocale: ^0.5.0
  better_player: ^0.0.82
  syncfusion_flutter_datepicker: ^20.3.50
  omni_datetime_picker: ^0.1.3
  time_range_picker : any
  syncfusion_flutter_calendar: ^20.3.57
  file_picker: ^5.2.5
  html_editor_enhanced: ^2.5.1
  menu_button: ^1.4.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.11.0
  build_runner: any
  retrofit: ^3.0.1
  retrofit_generator: ^4.0.1
  webviewx: ^0.2.1

  #flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true



  assets:
    # Add assets from the images directory to the application.
    - assets/images/profile.png
    - assets/images/store.png
    - assets/images/store_marker.png
    - assets/images/no-image.png
    - assets/images/promotion.jpg
    - assets/images/logo.png
    - assets/images/logo-no-bg.png
    - assets/images/pin.png
    - assets/countries.json
